tidelift: packagist/php-telegram-bot%2Ftelegram-bot-manager
patreon: phptelegrambot
liberapay: PHP-Telegram-Bot
open_collective: php-telegram-bot
ko_fi: phptelegrambot
custom: https://github.com/php-telegram-bot/telegram-bot-manager#donate
