language: php

cache:
    directories:
        - $HOME/.composer/cache

php:
    - 5.6
    - 7.0
    - nightly
    - hhvm

matrix:
    allow_failures:
        - php: nightly
        - php: hhvm
    fast_finish: true

notifications:
    on_success: never
    on_failure: always

git:
    depth: 1

install:
    - travis_retry composer install --prefer-dist --no-interaction

script:
    - |
        if [[ "$TRAVIS_PHP_VERSION" == "7.0" ]] ; then
            ./vendor/bin/phpunit --coverage-clover=coverage.xml
        else
            ./vendor/bin/phpunit
        fi

after_success:
    - if [[ "$TRAVIS_PHP_VERSION" == "7.0" ]]; then bash <(curl -s https://codecov.io/bash); fi
